# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QtPaintlayout.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(644, 640)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(95, 51, 511, 481))
        self.textBrowser.setObjectName("textBrowser")
        self.toolBox = QtWidgets.QToolBox(self.centralwidget)
        self.toolBox.setGeometry(QtCore.QRect(0, 0, 91, 211))
        self.toolBox.setObjectName("toolBox")
        self.Colors = QtWidgets.QWidget()
        self.Colors.setGeometry(QtCore.QRect(0, 0, 91, 157))
        self.Colors.setObjectName("Colors")
        self.listWidget = QtWidgets.QListWidget(self.Colors)
        self.listWidget.setGeometry(QtCore.QRect(0, 0, 256, 192))
        self.listWidget.setObjectName("listWidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.Colors)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, -1, 91, 151))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.toolBox.addItem(self.Colors, "")
        self.Brushes = QtWidgets.QWidget()
        self.Brushes.setGeometry(QtCore.QRect(0, 0, 91, 157))
        self.Brushes.setObjectName("Brushes")
        self.listView = QtWidgets.QListView(self.Brushes)
        self.listView.setGeometry(QtCore.QRect(0, 0, 256, 192))
        self.listView.setObjectName("listView")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.Brushes)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, -1, 91, 161))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.toolBox.addItem(self.Brushes, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 644, 21))
        self.menubar.setObjectName("menubar")
        self.menuQTPaint = QtWidgets.QMenu(self.menubar)
        self.menuQTPaint.setObjectName("menuQTPaint")
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menuQTPaint.menuAction())

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.Colors), _translate("MainWindow", "Page 1"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.Brushes), _translate("MainWindow", "Page 2"))
        self.menuQTPaint.setTitle(_translate("MainWindow", "QTPaint"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
